### ISSUE TITLE
Feature request: Behaviour if no icon is found

### ISSUE THREAD

**Issue by chrfickinger** [rasteiner/k3-awesome-picker#12]
What do you think about showing an additional icon if the search term does not match?

e.g.
![sc](https://user-images.githubusercontent.com/91317/96544261-7ca52180-12a6-11eb-8d24-602212d6280e.jpg)

**Comment by chrfickinger** [comment]
I also added the following css paramters for e better optical consistency and a small shadow for a better visualization of the floating window in my setup.

```css
div.afp-dropdown-container div.afp-dropdown div.afp-dropdown--searchbox {
    background-color: #fff;
    box-shadow: 0 8px 10px -4px rgba(0,0,0, .15);
}
```
But this can be done by custom stylesheets of course :-)
