### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Werbschaft** [rasteiner/k3-awesome-picker#4]
When using the Picker with the Font Awesome Pro Version the search doesn't work, I get the attached error.

<img width="679" alt="Bildschirmfoto 2020-10-19 um 09 35 39" src="https://user-images.githubusercontent.com/2178466/96415328-b6b2ec80-11ee-11eb-9597-b1801211c34c.png">

**Comment by rasteiner** [comment]
could you share a single icon declaration from your icons.yml? 

free icons look like this:
```yml
accessible-icon:
  changes:
    - 5.0.0
  label: Accessible Icon
  search:
    terms:
      - accessibility
      - handicap
      - person
      - wheelchair
      - wheelchair-alt
  styles:
    - brands
  unicode: f368
  voted: false
```

do pro version icons look different?

**Comment by Werbschaft** [comment]
Here are a few examples

```
500px:
  changes:
    - '4.4'
    - 5.0.0
  label: 500px
  search:
    terms: []
  styles:
    - brands
  unicode: f26e
  voted: false
abacus:
  changes:
    - 5.3.0
  label: Abacus
  search:
    terms:
      - addition
      - ancient
      - arithmetic
      - calculator
      - counting
      - hexadecimal
      - math
      - subtraction
  styles:
    - solid
    - regular
    - light
    - duotone
  unicode: f640
  voted: false
accessible-icon:
  changes:
    - 5.0.0
  label: Accessible Icon
  search:
    terms:
      - accessibility
      - handicap
      - person
      - wheelchair
      - wheelchair-alt
  styles:
    - brands
  unicode: f368
  voted: false
```
